import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const host = await readFile(new URL('../multiplayer-v2.js', import.meta.url), 'utf8');
const guest = await readFile(new URL('../multiplayer-room.html', import.meta.url), 'utf8');
const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const worker = await readFile(new URL('../worker/src/index.js', import.meta.url), 'utf8');
const social = await readFile(new URL('../social.js', import.meta.url), 'utf8');

assert.match(host, /canvas\.captureStream\(30\)/);
assert.match(host, /#neo-multiplayer-panel\{top:auto/);
assert.match(host, /event\.composedPath\(\)/);
assert.match(host, /!path\.includes\(panel\) && !room/);
assert.doesNotMatch(host, /neo-multi-toggle/);
assert.match(host, /neo_multiplayer_create_pending/);
assert.match(host, /pending\?\.expiresAt > Date\.now\(\)/);
assert.match(host, /neo-multi-lobby-state/);
assert.match(host, /AGUARDANDO JOGADOR 2/);
assert.match(host, /neo-wait-dots/);
assert.match(host, /neoLobbyGlow/);
assert.match(host, /A partida ficará pronta/);
assert.match(host, /function renderInviteQr/);
assert.match(host, /neo-multi-qr-code/);
assert.match(host, /qrcodejs\/1\.0\.0\/qrcode\.min\.js/);
assert.match(host, /ENTRAR PELO CELULAR/);
assert.match(host, /neo-multi-qr-code canvas\{display:none!important\}/);
assert.match(host, /async function autoCreateRoom/);
assert.match(host, /PREPARANDO SALA ONLINE/);
assert.match(host, /void autoCreateRoom\(\)/);
assert.match(host, /classList\.add\('open', 'lobby'\)/);
assert.match(host, /classList\.add\('playing'\)/);
assert.match(host, /neo-multi-session/);
assert.match(host, /PARTIDA INICIADA/);
assert.match(host, /atribuído automaticamente/);
assert.doesNotMatch(host, /querySelector\('#neo-multi-create'\)\.onclick/);
assert.match(host, /function resetRoomUi/);
assert.match(host, /function closeRoom/);
assert.match(host, /setTimeout\(\(\) => \{/);
assert.match(host, /Sessão online encerrada/);
assert.match(host, /createDataChannel\('neo-controls'/);
assert.match(host, /manager\.simulateInput\(seat - 1, index, value\)/);
assert.match(guest, /roomSystem === "ps1"/);
assert.match(guest, /\[\["□",1\],\["△",9\],\["×",0\],\["○",8\]\]/);
assert.match(guest, /roomSystem === "nes" \|\| roomSystem === "gba"/);
assert.doesNotMatch(host, /type:'assign'/);
assert.match(guest, /new RTCPeerConnection/);
assert.match(guest, /atribuído automaticamente/);
assert.match(guest, /-webkit-touch-callout: none/);
assert.match(guest, /contextmenu/);
assert.match(guest, /roomSystem === "megadrive"/);
assert.match(guest, /\[\["A",1\],\["B",0\],\["C",8\],\["X",10\],\["Y",9\],\["Z",11\]\]/);
assert.match(index, /JOGAR ONLINE/);
assert.match(index, /jogar-online\.png/);
assert.match(index, /on-transparent\.png/);
assert.match(index, /\/multiplayer\/rooms/);
assert.match(index, /neo_pending_multiplayer_room/);
assert.match(index, /neo_multiplayer_create_pending/);
assert.match(index, /multiplayer-game-picker/);
assert.match(index, /multiplayer-game-grid/);
assert.match(index, /renderMultiplayerGames/);
assert.match(index, /CRIAR NOVA PARTIDA/);
assert.match(index, /SALA E ESPECTADOR/);
assert.match(index, /multiplayer-account-note/);
assert.match(index, /ENTRAR OU CRIAR CADASTRO/);
assert.match(index, /neo_multiplayer_resume/);
assert.match(index, /resumeMultiplayerAfterAuth/);
assert.match(index, /requestMultiplayerAccount/);
assert.match(guest, /voltará automaticamente/);
assert.match(guest, /cadastro=1&return=/);
assert.match(guest, /ENTRAR OU CRIAR CADASTRO/);
assert.match(worker, /class MultiplayerRoom/);
assert.match(worker, /MULTIPLAYER_ROOMS\.getByName/);
assert.match(worker, /generate-ice-servers/);
assert.match(host, /\/multiplayer\/ice-servers/);
assert.match(guest, /\/multiplayer\/ice-servers/);
assert.doesNotMatch(guest, /stun\.cloudflare\.com:53/);
assert.match(host, /3\.5 \* 60 \* 60 \* 1000/);
assert.match(guest, /3\.5 \* 60 \* 60 \* 1000/);
assert.match(host, /CONVIDAR JOGADORES ONLINE/);
assert.match(worker, /class SocialPlayer/);
assert.match(worker, /\/social\/invite/);
assert.match(social, /\/social\/messages/);
assert.match(social, /message-avatar/);
assert.match(social, /message\.fromAvatar/);
assert.match(social, /new Notification/);
assert.match(worker, /fromAvatar: profile\.avatar/);
assert.match(worker, /profiles\/v1\//);
assert.match(worker, /presenceByUid/);
assert.match(social, /presence-dot/);
assert.match(social, /player\.online/);
assert.match(host, /EJS_emulator\?\.canvas/);
assert.match(host, /requestFrame/);
assert.doesNotMatch(guest, /ATIVAR SOM E JOGAR/);
assert.match(guest, /onconnectionstatechange/);
assert.match(guest, /if \(!peer\)\s+peer = new RTCPeerConnection/);
assert.match(guest, /const currentPeer = peer/);
assert.match(host, /collectScreenRecordingMediaTracks/);
assert.match(host, /Module\?\.AL\?\.currentCtx/);
assert.match(guest, /keyboardMap/);
assert.match(guest, /navigator\.getGamepads/);
assert.match(guest, /if \(!videoReady\)/);
assert.match(host, /audioTracks:mediaStream\.getAudioTracks/);
assert.match(guest, /function unlockPlayback/);
assert.match(guest, /requestFullscreen/);
assert.match(guest, /attachRemoteAudio/);
assert.match(guest, /id="remote-audio"/);
assert.match(guest, /remoteAudio\.srcObject = stream/);
assert.match(guest, /track\.contentHint = "music"/);
assert.match(guest, /remoteAudio\.play\(\)/);
assert.doesNotMatch(guest, /createMediaStreamSource/);
assert.match(guest, /áudio não recebido do anfitrião/);
assert.match(worker, /automaticSeat/);
assert.match(worker, /type: "assignment", seat: automaticSeat/);
assert.match(host, /row\.remove\(\)/);
assert.match(host, /classList\.remove\('open'\)/);
assert.match(host, /entrou na sala! Controle/);
assert.doesNotMatch(host, /AJUDE SEM GASTAR/);
assert.doesNotMatch(host, /ABRIR SALA/);
assert.match(host, /Seu convite foi enviado com sucesso/);
assert.match(host, /data-share="whatsapp"/);
assert.match(host, /data-share="discord"/);
assert.match(host, /data-share="instagram"/);
assert.match(host, /data-share="facebook"/);
assert.match(host, /navigator\.share/);
assert.match(social, /Seu convite foi enviado com sucesso/);
assert.match(guest, /\/social\/events\?since=/);
assert.match(guest, /\/social\/heartbeat/);
assert.match(guest, /VER DEPOIS/);
assert.match(guest, /SAIR E ENTRAR/);
assert.match(guest, /Sua partida atual continuará normalmente/);
assert.match(guest, /pendingInvites/);
assert.match(guest, /socket\?\.close\(1000, "Entrando em outra sala"\)/);
assert.match(host, /function refreshAudioCapture/);
assert.match(host, /setInterval\(refreshAudioCapture, 200\)/);
assert.match(host, /node\.connect\(audioCaptureDestination\)/);
assert.match(host, /node\.disconnect\(audioCaptureDestination\)/);
assert.match(host, /mediaStream\.removeTrack\(oldTrack\)/);
assert.match(host, /if \(audioTrack\) mediaStream\.addTrack\(audioTrack\)/);
assert.match(guest, /const audioPlayback = audioTrackReceived[\s\S]*remoteAudio\.play\(\)[\s\S]*const videoPlayback = video\.play\(\)/);
assert.match(guest, /addEventListener\("touchstart", unlockPlayback/);
assert.doesNotMatch(guest, /async function unlockPlayback/);
assert.match(host, /audioCaptureContext !== context/);
assert.match(host, /sender\.replaceTrack\(replacementTrack\)/);
assert.match(guest, /track\.onmute/);
assert.match(guest, /track\.onunmute/);
assert.match(guest, /function resumeRemoteAudio/);
assert.match(guest, /remoteAudio\.addEventListener\("stalled"/);
assert.match(guest, /document\.addEventListener\("visibilitychange"/);
assert.match(host, /index >= 16 && index <= 23/);
assert.match(host, /value <= 0x7fff/);
assert.match(guest, /ANALÓGICO CIMA",19/);
assert.match(guest, /D-PAD CIMA",4/);
assert.match(guest, /"Z",12/);
assert.match(guest, /"C CIMA",23/);
assert.match(guest, /ArrowUp:19, ArrowDown:18, ArrowLeft:17, ArrowRight:16/);
assert.match(guest, /inputIndex >= 16 && inputIndex <= 23/);
assert.match(guest, /gamepad\.axes\[0\]/);
assert.match(guest, /gamepad\.axes\[1\]/);
assert.match(guest, /roomSystem = String\(data\.room\.system/);
assert.match(guest, /CONFIGURAR CONTROLE/);
assert.match(guest, /neo_multiplayer_bindings_/);
assert.match(guest, /function setKeyboardBinding/);
assert.match(guest, /function setGamepadBinding/);
assert.match(guest, /localStorage\.setItem\(bindingStorageKey\(\)/);
assert.match(guest, /RESTAURAR PADRÃO/);
assert.match(guest, /neo_multiplayer_bindings_v2_/);
assert.match(guest, /\[\["B",1\],\["C↑",23\],\["A",0\],\["C↓",22\]\]/);
assert.match(guest, /@media \(max-width: 900px\) and \(orientation: portrait\)/);
assert.match(guest, /transform: scale\(1\.33334\)/);
assert.match(guest, /grid-template-columns: 1fr;/);
assert.doesNotMatch(guest, /grid-template-columns: 1fr 360px/);
assert.match(guest, /position: fixed;[\s\S]*max-height: 44dvh/);

console.log('multiplayer client and room: 124 checks passed');
