import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const host = await readFile(new URL('../multiplayer.js', import.meta.url), 'utf8');
const guest = await readFile(new URL('../multiplayer-room.html', import.meta.url), 'utf8');
const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const worker = await readFile(new URL('../worker/src/index.js', import.meta.url), 'utf8');
const social = await readFile(new URL('../social.js', import.meta.url), 'utf8');

assert.match(host, /canvas\.captureStream\(30\)/);
assert.match(host, /createDataChannel\('neo-controls'/);
assert.match(host, /manager\.simulateInput\(seat - 1, index, value\)/);
assert.doesNotMatch(host, /type:'assign'/);
assert.match(guest, /new RTCPeerConnection/);
assert.match(guest, /SOLICITAR|Aguardando aprovação/);
assert.match(index, /JOGAR ONLINE/);
assert.match(index, /\/multiplayer\/rooms/);
assert.match(index, /neo_pending_multiplayer_room/);
assert.match(guest, /voltará automaticamente/);
assert.match(worker, /class MultiplayerRoom/);
assert.match(worker, /MULTIPLAYER_ROOMS\.getByName/);
assert.match(worker, /generate-ice-servers/);
assert.match(host, /\/multiplayer\/ice-servers/);
assert.match(guest, /\/multiplayer\/ice-servers/);
assert.doesNotMatch(guest, /stun\.cloudflare\.com:53/);
assert.match(host, /3\.5 \* 60 \* 60 \* 1000/);
assert.match(guest, /3\.5 \* 60 \* 60 \* 1000/);
assert.match(host, /CONVIDAR JOGADORES ONLINE/);
assert.match(host, /\.ejs_menu_bar/);
assert.match(worker, /class SocialPlayer/);
assert.match(worker, /\/social\/invite/);
assert.match(social, /\/social\/messages/);
assert.match(worker, /profiles\/v1\//);
assert.match(worker, /presenceByUid/);
assert.match(social, /presence-dot/);
assert.match(social, /player\.online/);
assert.match(host, /EJS_emulator\?\.canvas/);
assert.match(host, /requestFrame/);
assert.doesNotMatch(guest, /ATIVAR SOM E JOGAR/);
assert.match(guest, /onconnectionstatechange/);
assert.match(guest, /if \(!peer\)\s+peer = new RTCPeerConnection/);
assert.match(guest, /const currentPeer = peer/);
assert.match(host, /collectScreenRecordingMediaTracks/);
assert.match(host, /Module\?\.AL\?\.currentCtx/);
assert.match(guest, /keyboardMap/);
assert.match(guest, /navigator\.getGamepads/);
assert.match(guest, /if \(!videoReady\)/);
assert.match(host, /audioTracks:mediaStream\.getAudioTracks/);
assert.match(guest, /function unlockPlayback/);
assert.match(guest, /requestFullscreen/);
assert.match(guest, /attachRemoteAudio/);
assert.match(guest, /createMediaStreamSource/);
assert.match(guest, /áudio não recebido do anfitrião/);
assert.match(worker, /automaticSeat/);
assert.match(worker, /type: "assignment", seat: automaticSeat/);
assert.match(host, /row\.remove\(\)/);
assert.match(host, /classList\.remove\('open'\)/);
assert.match(host, /está conectado à sua sala como controle/);
assert.match(host, /Seu convite foi enviado com sucesso/);
assert.match(host, /data-share="whatsapp"/);
assert.match(host, /data-share="discord"/);
assert.match(host, /data-share="instagram"/);
assert.match(host, /data-share="facebook"/);
assert.match(host, /navigator\.share/);
assert.match(social, /Seu convite foi enviado com sucesso/);

console.log('multiplayer client and room: 57 checks passed');
