import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const home = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const index = home;

assert.match(index, /refreshPersonalHero = async function/);
assert.match(index, /const recent = historyData\.games\?\.\[0\]/);
assert.match(index, /id = 'personalized-hero'/);
assert.match(index, /button\.innerHTML = '<span>▶<\/span> CONTINUE'/);
assert.match(index, /cloudRequest\('\/club\/library'\)/);
assert.match(index, /slot\.slot === 'auto'/);
assert.match(index, /SEU ÚLTIMO JOGO/);
assert.match(index, /Promise\.allSettled\(fetchPromises\)/);
assert.match(index, /catalogCover \|\| savedFrame \|\| recent\.cover/);
assert.match(index, /showOnlyPlayedHeroes\(false\)/);
assert.match(index, /placeGuestPromosAfterLibraryOpening/);
assert.match(index, /LOCAL_HISTORY_KEY = 'neo_local_game_history_v1'/);
assert.match(index, /LOCAL_SAVE_STARTED_KEY = 'neo_anonymous_save_started_at'/);
assert.match(index, /purgeExpiredAnonymousProgress/);
assert.match(index, /migrateLocalProgressToProfile/);
assert.match(index, /slot=manual-\$\{slot\}/);
assert.match(index, /hero-slide:not\(\[hidden\]\)/);
assert.match(index, /historyRequest\('POST', \{ id:recent\.id/);
assert.match(index, /window\.startGame\(recent\.playUrl\)/);
assert.match(index, /heroSlideCount\(\)/);
assert.match(index, /autosaveHeroImage\(recent\.id\)/);
assert.match(index, /URL\.createObjectURL\(await response\.blob\(\)\)/);
assert.match(index, /saveLibrary\.manualSaveLimit === null \? 5/);
assert.match(index, /Math\.min\(5, Math\.max\(3, availableManualSlots\)\)/);
assert.match(index, /profileAtStart \? savedLibraryGames : historyGames/);
assert.match(index, /function appendGuestPromoSlides\(slides, dots\)/);
assert.match(index, /CRIAR CONTA GRÁTIS/);
assert.match(index, /CONHECER FORMAS DE APOIAR/);
assert.match(index, /savedFrames = await Promise\.all/);
assert.match(index, /isAtariHistoryGame\(game\) \? '' : autosaveHeroImage/);
assert.match(index, /atariCoverOnly[\s\S]*?catalogCover \|\| recent\.cover/);
assert.match(index, /RECENTE \$\{recentIndex \+ 1\} DE \$\{recentGames\.length\}/);
assert.match(index, /id = `personalized-hero-\$\{recentIndex\}`/);
assert.match(index, /id="hero-prev"/);
assert.match(index, /id="hero-next"/);
assert.doesNotMatch(index, /imagem da partida aparecerá aqui depois do próximo autosave/);

assert.match(home, /let personalHeroRefreshVersion = 0/);
assert.match(home, /const refreshVersion = \+\+personalHeroRefreshVersion/);
assert.match(home, /const profileAtStart = accountProfile/);
assert.match(home, /refreshVersion !== personalHeroRefreshVersion \|\| profileAtStart !== accountProfile/);
assert.match(home, /function placeGuestPromosAfterLibraryOpening\(\)[\s\S]*?if \(accountProfile \|\| auth\.currentUser \|\| discordAccountToken\) return;/);
assert.match(home, /const authenticated = Boolean\(accountProfile \|\| auth\.currentUser \|\| discordAccountToken\)/);
assert.match(home, /indexData\.find\(game => catalogMatchesSave\(game, recent\)\)/);
assert.match(home, /systems\/neogeo\/games\.json\?v=20260831-history2/);
assert.match(home, /assets\/imagens-videos\/discord-icon\.svg\?v=2/);
assert.match(home, /String\(value \|\| ''\)\.split\(\/\[\?#\]\//);
assert.match(home, /const savedLibraryGames = \(saveLibrary\.games \|\| \[\]\)\.map/);
assert.match(home, /profileAtStart \? savedLibraryGames : historyGames/);
assert.match(home, /playUrl:historyGame\?\.playUrl \|\| catalogGame\?\.playUrl \|\| ''/);

console.log('wallpapers personalizados: corrida de login e promoções de visitante protegidas');
